### PR TITLE
fix: Empty (or cancelled request for) proxy credentials

### PR DESCRIPTION
**Pull request by ArtsiomCh**
Will fix [IllegalStateException](https://sentry.io/organizations/snyk/issues/3261803243/?referrer=slack)

### CODE REVIEW

**Comment by bastiandoetsch** [comment]
Maybe also add NOPROXY :)

**Comment by bastiandoetsch** [comment]
https://superuser.com/questions/944958/are-http-proxy-https-proxy-and-no-proxy-environment-variables-standard

**Comment by bastiandoetsch** [comment]
image

**Comment by ArtsiomCh** [comment]
> Maybe also add NOPROXY :)

@bastiandoetsch Didn't get it. What is that and where to add it?

**Comment by ArtsiomCh** [comment]
> Maybe also add NOPROXY :)

Looks like quit a huge of task with some unknowns in it. Lets leave it for the future when such request come out from our users.

**Pull request merged**
