### PR TITLE
Fix: existing unit tests

### PR DESCRIPTION
**Pull request by aldanchenko**
Existing tests were made as console applications and there was no IntelliJ plugin test. 

Replaced console applications with unit tests and added IntelliJ plugin integration test.

Replace TestParseUserInfo console application test with SnykUserResponseTest unit test.
Replace PreviewHtmlUi$ console application test with MiniServerTest unit test.
Replace SendSegmentTestEvent console application test with SegmentApiTest unit test.
Replace SendSegmentTestEvent console application test with SegmentApiTest unit test.
Replace TestMiniVuln2 console application test with MiniVulnerabilityTest unit test.
Replace TestParseResponse console application test with SnykVulnResponseTest unit test.
Replace TestUserInfoEndpoint console application test with ApiClientTest unit test.
Replace TestUserInfoEndpoint console application test with ApiClientTest unit test.
Add basic IntelliJ integration test for Snyk plugin with Maven support.

### CODE REVIEW

**Comment by aldanchenko** [comment]
>importProject - where does it import a project to?
It uses IntelliJ temp directory. IntelliJ can use OS temp directories for it.

>When the tests will be run?
It will run on verifyPlugin Gradle task.

**Comment by aldanchenko** [comment]
I'm sorry, Yulia. To fix branch name I renamed the branch to fix/existing-unit-tests and made another pull request. I will delete this one after we merge the proper branch if you don't mind.

**Comment by yuliabaron** [comment]
> > It will run on verifyPlugin Gradle task.
when installing the plugin you mean?

**Comment by aldanchenko** [comment]
>when installing the plugin you mean?

I tried to find more information about this Gradle task, but as I understand it's an independent task. We chat with the developer of this plugin. I'm waiting for an answer from him.

**Comment by aldanchenko** [comment]
I can change the settings so that the tests run before buildPlugin Gradle task.

**Pull request merged**
