### PR TITLE
feat: ✨ allow insecure CLI downloads when custom ca setting is set [ROAD-510]

### PR DESCRIPTION
**Pull request by bastiandoetsch**

### CODE REVIEW

**Review by aldanchenko — APPROVED** [review]
LGTM 👍

**Comment by aldanchenko** [comment]
But maybe someone else could look more deeper

**Review by ArtsiomCh — APPROVED** [review]
LGTM

**Comment by ArtsiomCh** [comment]
@bastiandoetsch please update CHANGELOG and merge before master will goes to far :)

**Pull request merged**
