### PR TITLE
chore: 💄 don't flood user with notifications when no OSS / IaC files are found [ROAD-477]

### PR DESCRIPTION
**Pull request by bastiandoetsch**
- removed balloons for oss and iac
image
image

### CODE REVIEW

**Comment by ArtsiomCh** [comment]
Looks good.
We only need to address Georgi's request to show initial error message when user click on such node with "No files/manager found"
image
PS not sure if that request is in the scope of that ticket.
PSS also GGH action to run tests need to be restarted somehow...

**Comment by bastiandoetsch** [comment]
Yeah, it's out of scope, but I've added a ticket as a feature-story.

**Comment by bastiandoetsch** [comment]
Rebased against master

**Comment by bastiandoetsch** [comment]
@ArtsiomCh could you please approve? Had to integrate with master anyway, so checks are now running and will hopefully return this time.

**Review by ArtsiomCh — APPROVED** [review]
LGTM

**Pull request merged**
