### PR TITLE
fix: show container specific message on macOS [ROAD-910]

### PR DESCRIPTION
**Pull request by ArtsiomCh**
image
image

### CODE REVIEW

**Comment by ArtsiomCh** [comment]
@bastiandoetsch please, would you mind to check when time permit if it works on macOS?...

**Comment by bastiandoetsch** [comment]
I'm not a 100% sure what I should see, but I think it's not correct: 
image

If this is not what's expected, let's take some time today to pair on it until it works.

**Comment by ArtsiomCh** [comment]
@bastiandoetsch try my 2nd attempt please when time permit.
Here I was inspired by your idea of extra rows/columns for alignment to put there some spacer. That allowed us to use "pure" panelGridConstraints() without `fill = GridConstraints.FILL_HORIZONTAL` which seems to be the main suspect of 0 height at resulted JEditorPane

**Review by aldanchenko — APPROVED** [review]
LGTM 👍

**Pull request merged**
