### PR TITLE
fix: 🐛 get sha256 before starting download, fix bug in error handler,…

### PR DESCRIPTION
**Pull request by bastiandoetsch**
… triggering download twice [ROAD-489]

[ROAD-489]: https://snyksec.atlassian.net/browse/ROAD-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsiomCh** [comment]
@bastiandoetsch please check what's wrong with tests. Looks like it's unable to compile....

**Comment by bastiandoetsch** [comment]
force pushing now - there was a code-mixup.

**Comment by ArtsiomCh** [comment]
LGTM
Just tried to disable wifi while downloading and got what we see in sentry sometimes:
```
java.net.UnknownHostException: static.snyk.io
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1140)
	at kotlin.io.TextStreamsKt.readBytes(ReadWrite.kt:150)
	at io.snyk.plugin.services.download.CliDownloader.downloadFile(CliDownloader.kt:42)
	at io.snyk.plugin.services.download.CliDownloaderErrorHandler$retryDownload$$inlined$runBackgroundableTask$1.run(progress.kt:36)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Looks like we need more broad catch at `SnykCliDownloaderService#downloadLatestRelease` when calling `downloader.downloadFile`
Shell we address that here or at separate ticket/PR?

**Comment by bastiandoetsch** [comment]
I'd add it here - good catch (no pun intended)

**Comment by bastiandoetsch** [comment]
Did you get the error balloon shown?

**Comment by ArtsiomCh** [comment]
I got it as exception. 
Looks like we need to move `try catch` into BackgroundableTask, cause otherwise it happened in another thread
PS Also did report to Senrty but don't se it there...

**Comment by ArtsiomCh** [comment]
Seems like messages need to be adjusted as we don't download CLI from GitHub anymore: https://github.com/snyk/snyk-intellij-plugin/issues/215
PS Also would be interesting to investigate why download fails in that case.

**Comment by bastiandoetsch** [comment]
@ArtsiomCh Wanna review again? 

- updated error message and removed reference to github
- moved try-catch blocks for download and ignore tasks inside the task 
- rebased the branch to latest master

**Review by ArtsiomCh — APPROVED** [review]
LGTM

**Pull request merged**
