### PR TITLE
Feat: ignore IaC errors about broken JSON files [ROAD-1201]

### PR DESCRIPTION
**Pull request by asaf92**
### Description

Ignore IaC errors about broken JSON syntax

### Checklist

- [ ] Tests added and all succeed
- [ ] Linted
- [ ] CHANGELOG.md updated
- [ ] README.md updated, if user-facing

### CODE REVIEW

**Comment by j-luong** [comment]
What happens when a valid IAC file is malformed? It gets ignored too?

**Comment by michelkaporin** [comment]
@j-luong apparently yes, as it'll be reported as error with `2105` error code by IaC scan.

**Comment by j-luong** [comment]
might be worth putting that caveat in the README?

**Comment by michelkaporin** [comment]
@j-luong I'd keep product logic out of the language server documentation scope as much as possible, since it will get stale here as soon as IaC team change their logic. [The code](https://github.com/snyk/snyk-intellij-plugin/blob/1bd20620f8788593b3a24200e78e6980887523ef/src/main/kotlin/snyk/iac/IacResult.kt#L34) is covering this case.

**Comment by michelkaporin** [comment]
@j-luong Also [let's see](https://github.com/snyk/snyk-ls/pull/173#issuecomment-1305253111) if IaC team covers it in the docs already.

**Review by michelkaporin — APPROVED** [review]
Reviewed by @asaf92 ✅

**Pull request merged**
